"""empty message

Revision ID: 7d18b50c299d
Revises: 807b814ee33f
Create Date: 2024-04-10 18:59:08.863679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d18b50c299d'
down_revision = '807b814ee33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_music', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###
