"""empty message

Revision ID: 807b814ee33f
Revises: cf8db0b6771c
Create Date: 2024-04-10 18:45:52.482425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807b814ee33f'
down_revision = 'cf8db0b6771c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sheet_music')
    # ### end Alembic commands ###
