"""empty message

Revision ID: a372dec740f3
Revises: 7d18b50c299d
Create Date: 2024-04-10 20:02:51.117694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a372dec740f3'
down_revision = '7d18b50c299d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_music', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', mysql.VARCHAR(length=300), nullable=False))

    # ### end Alembic commands ###
