"""empty message

Revision ID: e74b02a9060f
Revises: a372dec740f3
Create Date: 2024-04-27 13:48:12.252539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e74b02a9060f'
down_revision = 'a372dec740f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=300), nullable=True))
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', mysql.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
